bsc-wdc/dislib

dislib/data/base.py
This is because PyCOMPSs currently does not support single character parameters in tasks (#15)
Default delimiter is set to ","
=> Removed delimited parameter from load_csv methods

.gitignore
Log files must be ignored by git. So far, only tests generate 'output.log', but still.
=> Git Ignore '.log' files.

dislib/classification/csvm/base.py, requirements.txt, tests/test_csvm.py
Created a simple usage example for C-SVM. 
During the creation of the example, I realized that gamma='scale' was not correctly working because it is not supported in scikit-learn 0.19, and because there was a bug in the method that checks the convergence of the model.
I have updated the requirements to the latest scikit-learn version, and removed gamma='scale' as computing X.std() would be expensive. Instead gamma='auto' is the default value for gamma. I have added a test that checks that gamma='auto' now works properly.
=> Csvm gamma

README.md, examples/rf_iris.py
I have rewritten a bit the README.md so that 1st users do not encounter path problems using docker. 
The previous example used GUI to plot the results (which is not supported in docker dislib) so I've changed the example to rf_iris.py (the only one which does not require external datasets).
@salvisolamartinell I have changed a bit the rf_iris.py to be more verbose and a bit cleaner for people who is just starting to use the dislib. Review the changes and tell if they're OK for you.
=> Improved 1st steps and clarified dislib docker limitations

dislib/classification/rf/decision_tree.py, dislib/classification/rf/forest.py, tests/test_rf.py
Decision tree predict_proba was not working if while building it the `use_sklearn and n_features * len(sample) <= sklearn_max` of the _compute_build_subtree method was False. In this conditions, _InnerNodeInfo and _LeafInfo objects appear and the _Node.predict_proba() wasn't working for these objects. This has been fixed now.
Fixes #114
Use a very big dataset or manually set `sklearn_max=10`, and call rf.predict_proba(dataset).
=> rf: fixed predict_proba

examples/rf_iris.py
rf_iris.py used a rf.preict(dataset) an then used the same dataset for rf.score(dataset), but the labels of the original dataset ('true' labels) which score() needs had been changed by predict(). This has been fixed reloaing the dataset. Also, dataset.labels property is used to simplify the code.
runcompss --python_interpreter=python3 ./examples/rf_iris.py
=> rf_iris example small fixes

dislib/data/base.py, dislib/data/classes.py, tests/test_data.py
Added:
* Dataset.transpose() for both dense and sparse (csr) matrices. Labels are discarded when doing the transpose.
* Dataset.subsets_sizes() wrapper for dataset.subset_size(i) which returns all subset's sizes.
Fixes:
* Minor changes to keep samples type when updating them in update_samples and have a single version for sparse/dense.
* Renamed some tests to make them less verbose.
* DataTest.test_transpose_sparse
* DataTest.test_transpose_dense
* DataTest.test_subsets_sizes
=> Dataset Transpose implementation

tests/test_csvm.py
This PR changes CSVMTest.test_sparse to check the support vectors and dual coefficients instead of the predicted labels because of #145
=> Check SVs and coefficients in CSVMTest.test_sparse

dislib/classification/csvm/base.py, dislib/cluster/gm/base.py, dislib/data/classes.py, tests/test_data.py
Move the logic that creates ids for each element in a Subset and uses them for the optional remove_duplicates to the CSVM module. Test for Subset removed.
Fixes #178
I checked that the current tests cover the 'remove duplicates' logic.
=> Move remove duplicates logic to CSVM module

dislib/cluster/gm/base.py, tests/test_gm.py
Added a sparse data test, equivalent to the one in KMeans, to GaussianMixture. Adapted GaussianMixture module to support sparse data. Now it works using csr_matrix for Subset.samples.
Fixes #136
Reproduce instructions: see GaussianMixtureTest.test_sparse
=> Adapt GaussianMixture to sparse data

dislib/cluster/gm/base.py, dislib/recommendation/als/base.py, docs/source/dislib.rst, examples/gm_covariance_types_comp.py, tests/test_gm.py
Added support for covariance_type='tied', 'diag', and 'spherical':
- 'tied' (all components share the same general covariance matrix),
- 'diag' (each component has its own diagonal covariance matrix),
- 'spherical' (each component has its own single variance).
With the already supported covariance_type='full', this completes the 4 covariance types present in scikit-learn.
The _test_sparse_ has been expanded to check that the new types work on dense and sparse datasets. A _test_covariance_types_ has been added, which compares the weaker or stronger clustering of the different types on 4 carefully crafted datasets. A graphical plot of this comparison has been added at examples/gm_covariance_types_comparision.py.
Also: improvements of the documentation, increased parameter validation and …
=> Gaussian mixture: added covariance types 'tied', 'diag' and 'spherical', and extra tests

dislib/cluster/dbscan/classes.py, examples/dbscan-driver.py
In the _compute_neighbours task (inside the partial_dbscan), the neighbors are computed for each sample in the region (in chunks of max_samples elements). This used pairwise_distances, computing the distances to all the points in the same region and neighboring regions. This has been modified to use sklearn.neighbors.NearestNeighbors.radius_neighbors(), avoiding the need to compute all the distances. Performance of this task has improved a lot in a large execution in MN4.
Fixes #193
Run the tests in local and an execution in MN4 before and after.
IN MN4, with a dislib installation loaded:
`enqueue_compss -t --qos=debug --scheduler=es.bsc.compss.scheduler.fifoDataScheduler.FIFODataScheduler --worker_in_master_cpus=0 --cpus_per_node=30 --worker_working_dir=<gpfs or …
=> DBSCAN: radius_neighbors instead of pairwise_distances in partial_dbscan

dislib/cluster/dbscan/base.py, dislib/cluster/dbscan/classes.py, tests/test_dbscan.py
Fixed the bugs from #199, with a significant refactor of the `_compute_neighbors()`, `_compute_labels()` (now `_compute_cp_labels()`) and `_get_equivalences()` tasks. Added more comprehensive tests to check these bugs.
The serialization/deserialization of the neighbors list was the main bottleneck, and this problem was worsened by using them in another task. To reduce the problem, neighbors have been split in different classes (neighbors of non-core points, neighbors of core points within the region and neighbors of core points outside of the region) to be used by different tasks. Furthermore, performance has been improved by using only one-directional neighbouring relations when possible. 
Experimental observations:
- The main bottleneck is still the serialization/deserialization of all …
=> DBSCAN: bug fixes and performance optimizations

dislib/regression/__init__.py, dislib/regression/linear/base.py, docs/source/api-reference.rst, docs/source/dislib.regression.linear.rst, docs/source/dislib.rst, examples/linear_regression_plot.py, tests/test_gm.py, tests/test_linear_regression.py
Added new module for (simple) linear regression. It is based on the algorithm we had in the apps repository: a simple linear regression (1 explanatory variable, 1 dependent variable). The model is a line `y = alpha + beta*x`. The attribute names are `coef_` and `intercept_`, as in scikit-learn.
The scikit-learn implementation supports multiple linear regression (multiple explanatory variables). To do that, we would need a new implementation, because the underlying calculations are different (matrix based).
Fixes #201 
An script which plots the regression of a simple example has been added in the examples folder.
=> Added simple linear regression

dislib/classification/rf/decision_tree.py, dislib/regression/linear/base.py, tests/test_rf.py
Fixed a bug in the DecisionTree predict_proba() method that caused the probability in impure leaf nodes not to be computed (the probability was casted from float to int and thus converted to 0 if it was <1). This worsened the accuracy of the algorithm in some cases.
The fix shouldn't have any impact on running time.
The new test case, RFTest.test_iris, tests the RandomForestClassifier with n_estimators=1 and max_depth=1 (to have impure leaves). Before the fix, the accuracy was 0.333... and after the fix it can go up to 0.666..., having same values and variability as sklearn reuslts.
The new test case can be tested with the new and the old codebase. The equivalent code in sklearn is very similar. Running them on a loop and printing the accuracies doesn't show any …
=> rf: fixed predict_proba bug

QUICKSTART.md, bin/dislib, bin/dislib_cmd.py, docker/Dockerfile, docs/source/development.rst
This pull requests adds minor fixes to allow jupyter to be run inside dislib docker container. This PR can be tested following the updated instructions on Quickstart.md. 
The current `bscwdc/dislib:latest` docker image pushed to dockerhub already contains jupyter. To update the local latest image first remove it using `docker rmi bscwdc/dislib:latest` and then proceed with the quickstart instructions to run jupyter inside dislib's container.
Running the jupyter notebook inside the `./notebooks' folder as described in the docs section Quickstart.
=> Support for jupyter in docker

dislib/decomposition/pca/base.py, dislib/regression/linear/base.py, tests/test_linear_regression.py, tests/test_pca.py
Support for sparse arrays in PCA. For LinearRegression, a NotImplementedError is raised.
=> PCA sparse support, LR to raise error

docs/source/conf.py
Fixed docs link docs to source file for objects that are not defined in the same source file (for example, when objects are imported and added to `__all__`).
The generated docs are available [here](https://dislib.bsc.es/en/issue-259/).
Fixes #259
=> Fixed docs links to source for objects in __all__

dislib/model_selection/_split.py, tests/test_gridsearch.py
`KFold` parameter `shuffle` was set to `True` by default, in opposition to the documentation. This caused `GridSearchCV` not to be reproducible even with reproducible estimators.
I've set `KFold(..., shuffle=False)`.
The fix caused a test of GridSearchCV with CascadeSVM to fail, because CascadeSVM needs to have the 2 classes in each data partition. I fixed it adding an initial preshuffle of the dataset in the test.
Fixes #265
- Bug fix (non-breaking change which fixes an issue)
- [N/A] I have commented my code, particularly in hard-to-understand areas.
- [N/A] I have documented the public methods of any public class according to the guide styles. 
- [N/A] I have made corresponding changes to the documentation
=> Make KFold not to shuffle by default

docs/source/conf.py
Changed how the documentation is built so that the source links point to the proper version in github. 
However, this will not work for the 'latest' version of the documentation (that should point to the 'master' branch) because the version of the code is read from the VERSION file. And the VERSION file contains an X.Y.Z number.
There are two possible solutions for this:
- Deactivate the latest version of the documentation as it is unstable anyways (and I am not sure if users should be checking it)
- Place a `0.0.0` or something like that in the VERSION file of the master branch to indicate that we are in the master branch.
FIxes #261
=> Docs source now points to proper release

dislib/model_selection/_split.py, tests/test_gridsearch.py
The method `merge_slices(s1, s2)` added the regular blocks of `s1` and `s2` to the merged array. When there was no regular block in one of the slices, an empty row block was added to the result and an error was eventually raised.
This case happened when the KFold size was less than 2 times the number of rows in a regular block, i.e., when having few blocks and high number of folds.
The fix was a simple check for empty ds-arrays.
Fixes #267
- [N/A] I have commented my code, particularly in hard-to-understand areas.
- [N/A] I have documented the public methods of any public class according to the guide styles. 
- [N/A] I have made corresponding changes to the documentation
=> Fixing empty blocks issue in merge_slices() for GridSearchCV

bin/dislib
Fixed dislib executable for MacOS by replacing readlink with a different way of getting the script's path.
Fixes #239
=> Fixed dislib executable in MacOS

dislib/decomposition/pca/base.py, tests/test_pca.py
PCA transform() and fit_transform() returned a transformed_array ds-array with inconsistencies when n_components < n_features, including wrong shape and empty blocks, and miss-aligned block shapes. This bug has been fixed and a test for the checking the shape added.
- [NA] I have commented my code, particularly in hard-to-understand areas.
- [NA] I have documented the public methods of any public class according to the guide styles. 
- [NA] I have made corresponding changes to the documentation
=> fixed internal inconsistencies in transformed_array of PCA

examples/classifier_comparison.py
Fixed block_size in classifier_comparison.py (apparently now block_size cannot be bigger than the arrays shape).
Fixes #315
```
cd examples
python3 classifier_comparison.py
```
=> Fixed block_size in classifier_comparison.py

Jenkinsfile, docker/Dockerfile
Updated the docker-base Dockerfile to COMPSs/2.8 (just deployed to Dockerhub). With this we can use COMPSs2.8 features in dislib.
The installation of cvxpy==1.1.5 was failing. For some reason, its dependency scs was trying to install numpy 1.20 (although it is not listed as dependency) which is not compatible with the python3.6 of the base image ubuntu18.04. As a workaround, I preinstall scs with `pip3 install --no-deps scs`. All the tests work fine.
The run_ci_checks.sh script has been run on the new docker image.
=> Updated docker image to COMPSs/2.8

dislib/cluster/dbscan/classes.py
DBSCAN uses scipy's lil_matrix. It filled its rows with a numpy array, but this fails with recent versions of scipy (from 1.4... or 1.5...). The fix is converting the numpy array to a list with a tolist() call.
Our docker image has scipy 1.3 so this problem wasn't detected on the tests (I'll add an issue for updating the docker image).
=> Fixed bug on DBSCAN lil_matrix with recent versions of scipy

notebooks/estimators.ipynb
Fixed estimators notebook bugs with PCA (now pca.explained_variance_ and pca.components_ are ds-arrays, so they need to be collected before using as numpy arrays).
=> fixed estimators notebook bugs with PCA

dislib/math/base.py
AFAIU, this is equivalent, more readable, more compact, and more performant.
=> Improper use of combinations_with_replacement

docs/source/requirements.txt
There was a recent docutils-0.18 release that break the compilation.
Solution is to pin `docutils` version to `<0.18` in requirements
=> Fix Read the Docs compilation

docs/source/requirements.txt
There was a recent mistune-2.0.0 release that break the compilation.
Solution is to pin `mistune` version to `==0.8.4` in requirements
=> fix mistune package version doc compilation error

Dockerfile, MANIFEST.in, setup.py
When creating tar.gz file for distribution the files requirements.txt, VERSION and README.md were not included so the installation from sources failed.
=> fix setup missing files
